---
kind: pipeline
type: docker
name: build

default_build: &default_build
  image: golang
  commands:
    - go build -ldflags="-s -w" -o "${DRONE_REPO_NAME}-$${GOOS}-$${GOARCH}" .

steps:
  - <<: *default_build
    name: linux-amd64
    environment:
      GOOS: linux
      GOARCH: amd64
  - <<: *default_build
    name: linux-arm
    environment:
      GOOS: linux
      GOARCH: arm
  - <<: *default_build
    name: linux-arm64
    environment:
      GOOS: linux
      GOARCH: arm64
  - <<: *default_build
    name: freebsd-amd64
    environment:
      GOOS: freebsd
      GOARCH: amd64
  - <<: *default_build
    name: freebsd-arm
    environment:
      GOOS: freebsd
      GOARCH: arm
  - <<: *default_build
    name: darwin-amd64
    environment:
      GOOS: darwin
      GOARCH: amd64
  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: ${DRONE_REPO_NAME}-*
    when:
      event:
        - tag
