metrics:
# NSD Metrics
# Taken from https://nsd.docs.nlnetlabs.nl/en/latest/manpages/nsd-control.html#statistics-counters
  time.boot:
    help: 'uptime in seconds since the server was started. With fractional seconds.'
    type: gauge
  time.elapsed:
    help: 'time since the last stats report, in seconds. With  fractional seconds.'
    type: gauge
  size.db.disk:
    help: 'size of nsd.db on disk, in bytes.'
    type: gauge
  size.db.mem:
    help: 'size of the DNS database in memory, in bytes.'
    type: gauge
  size.xfrd.mem:
    help: 'size of memory for zone transfers and notifies in xfrd process, excludes TSIG data, in bytes.'
    type: gauge
  size.config.disk:
    help: 'size of zonelist file on disk, excludes the nsd.conf size, in bytes.'
    type: gauge
  size.config.mem:
    help: 'size of config data in memory, kept twice in server and xfrd process, in bytes.'
    type: gauge
  zone.master:
    help: 'number of master zones served. These are zones with no "request-xfr" entries.'
    type: counter
  zone.slave:
    help: 'number of slave zones served. These are zones with "request-xfr" entries.'
    type: counter
  zone.primary:
    help: 'number of primary zones served. These are zones with no "request-xfr" entries. Same as zone.master.'
    type: counter
  zone.secondary:
    help: 'number of secondary zones served. These are zones with "request-xfr" entries. Same as zone.slave.'
    type: counter
# Metrics that have labels based on some regex value
# The capture group index should match the index of the label name under labels
label_metrics:
  ([\w\-\.]*)\.?num\.queries:
    name: num_queries
    labels:
      - domain
    help: 'number of queries received (the tcp and udp queries added up).'
    type: counter
  ([\w\-\.]*)\.?num.edns$:
    name: num_edns
    labels:
      - domain
    help: 'number of queries with EDNS OPT.'
    type: counter
  ([\w\-\.]*)\.?num.ednserr:
    name: num_ednserr
    labels:
      - domain
    help: 'number of queries which failed EDNS parse.'
    type: counter
  ([\w\-\.]*)\.?num\.udp$:
    name: num_udp
    labels:
      - domain
    help: 'number of queries over UDP ip4.'
    type: counter
  ([\w\-\.]*)\.?num\.udp6:
    name: num_upd6
    labels:
      - domain
    help: 'number of queries over UDP ip6.'
    type: counter
  ([\w\-\.]*)\.?num\.tcp$:
    name: num_tcp
    labels:
      - domain
    help: 'number of connections over TCP ip4.'
    type: counter
  ([\w\-\.]*)\.?num\.tcp6:
    name: num_tcp6
    labels:
      - domain
    help: 'number of connections over TCP ip6.'
    type: counter
  ([\w\-\.]*)\.?num\.tls$:
    name: num_tls
    labels:
      - domain
    help: 'number of connections over TLS ip4. TLS queries are not part of num.tcp.'
    type: counter
  ([\w\-\.]*)\.?num\.tls6:
    name: num_tls6
    labels:
      - domain
    help: 'number of connections over TLS ip6. TLS queries are not part of num.tcp6.'
    type: counter
  ([\w\-\.]*)\.?num\.answer_wo_aa:
    name: num_answer_wo_aa
    labels:
      - domain
    help: 'number of answers with NOERROR rcode and without AA flag, this includes the referrals.'
    type: counter
  ([\w\-\.]*)\.?num\.rxerr:
    name: num_rxerr
    labels:
      - domain
    help: 'number of queries for which the receive failed.'
    type: counter
  ([\w\-\.]*)\.?num\.txerr:
    name: num_txerr
    labels:
      - domain
    help: 'number of answers for which the transmit failed.'
    type: counter
  ([\w\-\.]*)\.?num\.raxfr:
    name: num_raxfr
    labels:
      - domain
    help: 'number of AXFR requests from clients (that got served with reply).'
    type: counter
  ([\w\-\.]*)\.?num\.rixfr:
    name: num_rixfr
    labels:
      - domain
    help: 'number of IXFR requests from clients (that got served with reply).'
    type: counter
  ([\w\-\.]*)\.?num\.truncated:
    name: num_truncated
    labels:
      - domain
    help: 'number of answers with TC flag set.'
    type: counter
  ([\w\-\.]*)\.?num\.dropped:
    name: num_dropped
    labels:
      - domain
    help: 'number of queries that were dropped because they failed sanity check.'
    type: counter
  ([\w\-\.]*)\.?num\.type\.([\w\-]+):
    name: num_type
    labels:
      - domain
      - type
    help: 'number of queries with this query type.'
    type: counter
  ([\w\-\.]*)\.?num\.opcode\.(\w+):
    name: num_opcode
    labels:
      - domain
      - type
    help: 'number of queries with this opcode.'
    type: counter
  ([\w\-\.]*)\.?num\.class\.(\w+):
    name: num_class
    labels:
      - domain
      - class
    help: 'number of queries with this query class.'
    type: counter
  ([\w\-\.]*)\.?num\.rcode\.(\w+):
    name: num_rcode
    labels:
      - domain
      - rcode
    help: 'number of answers that carried this return code.'
    type: counter
  server(\d+)\.queries:
    name: server_queries
    labels:
      - server
    help: 'number of queries handled by the server process.'
    type: counter
